version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx:/var/lib/nginx

  db:
    image: mysql:5.7.22
    ports:
      - "6000:3306"
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 7000:80
    environment:
      - PMA_ARBITRARY=1
