version: '3.8'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    # ports:
    #   - 8000:8000
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"


  # admin_db:
  #   image: mysql:5.7.22
  #   environment:
  #     MYSQL_DATABASE: admin
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./storage/dbdata:/var/lib/mysql
  #   ports:
  #     - 33063:3306
  db:
    image: mysql:5.7.22
    ports:
      - "6000:3306"
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./storage/dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 7000:80
    environment:
      - PMA_ARBITRARY=1
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "7000:80"
  #   links:
  #     - db:db
  #   environment:
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
      # MYSQL_ROOT_PASSWORD:
    # networks:
    #   - app-network
